#!/bin/sh
# Quickstart setup for slackcat: generates a self-contained deployment directory
# (docker-compose.yml, .env, fusionauth-kickstart.json) for the whole system -
# postgres, seaweedfs, fusionauth, slackpack, slackback, slackopy.
#
# Safe to re-run: secrets already present in an existing .env are preserved (only
# missing ones are generated); docker-compose.yml and fusionauth-kickstart.json are
# always rewritten from the current templates, so re-running after pulling repo
# updates picks up changes without losing secrets or admin-supplied values.
#
# Usage: ./quickstart.sh <deploy-dir>
#
# Config-surface conventions (see DECISIONS.md):
#   - Internal wiring (role names, internal service/network names) is never
#     surfaced here - it's fixed in the generated docker-compose.yml.
#   - Environment topology: no reverse proxy is bundled and no host ports are
#     published. The deployment instead joins the admin's own already-existing
#     reverse-proxy Docker network (REVERSE_PROXY_NETWORK), matching how these
#     proxies are normally run.
#   - Secrets/values this script can generate itself are generated. Values only the
#     admin has (Slack credentials, real public domains, the proxy network name) are
#     prompted for interactively when a terminal is attached, or left blank for
#     manual entry otherwise.

set -eu

if [ $# -lt 1 ]; then
	echo "Usage: $0 <deploy-dir>" >&2
	exit 1
fi

DEPLOY_DIR="$1"
ENV_FILE="$DEPLOY_DIR/.env"

mkdir -p "$DEPLOY_DIR"

random_hex() {
	openssl rand -hex 24
}

random_uuid() {
	if command -v uuidgen >/dev/null 2>&1; then
		uuidgen
	else
		openssl rand -hex 16 | sed -E 's/(.{8})(.{4})(.{4})(.{4})(.{12})/\1-\2-\3-\4-\5/'
	fi
}

# Load already-generated values so re-running preserves them.
if [ -f "$ENV_FILE" ]; then
	# shellcheck disable=SC1090
	. "$ENV_FILE"
fi

# set_env NAME [generator]
# Keeps an already-set value from a previous run (or one already exported in the
# calling shell); otherwise runs the generator (if given) or leaves the value blank.
set_env() {
	name="$1"
	generator="${2:-}"
	eval "current=\${$name:-}"
	if [ -n "$current" ]; then
		return
	fi
	if [ -n "$generator" ]; then
		value="$("$generator")"
	else
		value=""
	fi
	eval "$name=\$value"
}

set_env POSTGRES_PASSWORD random_hex
set_env SLACKBACK_DB_PASSWORD random_hex
set_env FUSIONAUTH_DB_PASSWORD random_hex
set_env AUTH_SECRET random_hex
set_env FUSIONAUTH_API_KEY random_uuid
set_env FUSIONAUTH_APPLICATION_ID random_uuid
set_env FUSIONAUTH_CLIENT_SECRET random_hex
set_env FUSIONAUTH_ADMIN_PASSWORD random_hex

# prompt_env NAME LABEL [secret]
# Keeps an already-set value the same way set_env does. Otherwise, if a terminal is
# actually attached, asks for it interactively (so a first run doesn't need a manual
# .env edit afterward just to fill in the values nothing could sensibly default).
# Non-interactive invocations (no attached terminal - e.g. unattended automation)
# fall back to leaving it blank, same as before; the closing summary lists whatever's
# still missing either way.
prompt_env() {
	name="$1"
	label="$2"
	secret="${3:-}"
	eval "current=\${$name:-}"
	if [ -n "$current" ]; then
		eval "$name=\$current"
		return
	fi
	if [ ! -t 0 ]; then
		eval "$name="
		return
	fi
	if [ -n "$secret" ]; then
		printf '%s: ' "$label" >&2
		stty -echo 2>/dev/null
		read -r value
		stty echo 2>/dev/null
		printf '\n' >&2
	else
		printf '%s: ' "$label" >&2
		read -r value
	fi
	eval "$name=\$value"
}

prompt_env SLACK_AUTH_TOKEN "Slack auth token (xoxc-...)" secret
prompt_env SLACK_AUTH_COOKIE "Slack session cookie (the \"d\" cookie value, xoxd-...)" secret
prompt_env PUBLIC_DOMAIN "Public domain for slackopy (e.g. slack.example.com)"
prompt_env FUSIONAUTH_PUBLIC_DOMAIN "Public domain for FusionAuth (e.g. auth.example.com)"
prompt_env FILES_PUBLIC_DOMAIN "Public domain for archived files (e.g. files.example.com)"
prompt_env REVERSE_PROXY_NETWORK "Name of your existing reverse-proxy's Docker network to join (e.g. the network your Nginx Proxy Manager/Traefik container is already on)"

cat >"$ENV_FILE" <<ENVEOF
# Generated by quickstart.sh - re-running preserves these values.

# --- Fill in before starting (no sensible default exists) ---
# Slack workspace credentials for the workspace being archived (xoxc token + "d" session cookie)
SLACK_AUTH_TOKEN=$SLACK_AUTH_TOKEN
SLACK_AUTH_COOKIE=$SLACK_AUTH_COOKIE
# Real public domain slackopy will be reached at - point your reverse proxy here
PUBLIC_DOMAIN=$PUBLIC_DOMAIN
# Real public domain FusionAuth will be reached at - must be reachable directly by
# end-user browsers (the login redirect goes here), not just internally
FUSIONAUTH_PUBLIC_DOMAIN=$FUSIONAUTH_PUBLIC_DOMAIN
# Real public domain archived files will be reached at (served by SeaweedFS)
FILES_PUBLIC_DOMAIN=$FILES_PUBLIC_DOMAIN
# Name of your already-existing reverse-proxy Docker network (e.g. Nginx Proxy
# Manager's or Traefik's own network) - this deployment joins it, not the other way
# around, since the proxy is the shared, standing piece of infrastructure here
REVERSE_PROXY_NETWORK=$REVERSE_PROXY_NETWORK

# --- Generated automatically - safe to leave as-is ---
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
SLACKBACK_DB_PASSWORD=$SLACKBACK_DB_PASSWORD
FUSIONAUTH_DB_PASSWORD=$FUSIONAUTH_DB_PASSWORD
AUTH_SECRET=$AUTH_SECRET
FUSIONAUTH_API_KEY=$FUSIONAUTH_API_KEY
FUSIONAUTH_APPLICATION_ID=$FUSIONAUTH_APPLICATION_ID
FUSIONAUTH_CLIENT_SECRET=$FUSIONAUTH_CLIENT_SECRET
FUSIONAUTH_ADMIN_PASSWORD=$FUSIONAUTH_ADMIN_PASSWORD
ENVEOF

cat >"$DEPLOY_DIR/docker-compose.yml" <<'COMPOSEEOF'
services:
  slackcat-postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: slackcat
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: slackcat
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U slackcat"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  slackcat-seaweedfs:
    image: chrislusf/seaweedfs
    restart: unless-stopped
    # -ip.bind must be explicit: -ip alone controls both the advertised address AND
    # what the listener binds to.
    command: server -dir=/data -master.volumeSizeLimitMB=1024 -ip=slackcat-seaweedfs -ip.bind=0.0.0.0
    # Also on "proxy" (the admin's existing reverse-proxy network) since archived
    # files need to be reachable externally - unlike postgres/slackpack/slackback,
    # which only ever talk to each other and stay on the internal "default" network.
    networks:
      - default
      - proxy
    volumes:
      - seaweedfs-data:/data

  slackcat-fusionauth-db:
    image: postgres:16.0-bookworm
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${FUSIONAUTH_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - fusionauth-db-data:/var/lib/postgresql/data

  slackcat-fusionauth:
    image: fusionauth/fusionauth-app:latest
    restart: unless-stopped
    depends_on:
      slackcat-fusionauth-db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://slackcat-fusionauth-db:5432/fusionauth
      DATABASE_ROOT_USERNAME: postgres
      DATABASE_ROOT_PASSWORD: ${FUSIONAUTH_DB_PASSWORD}
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: ${FUSIONAUTH_DB_PASSWORD}
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_RUNTIME_MODE: production
      FUSIONAUTH_APP_URL: http://slackcat-fusionauth:9011
      FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart/kickstart.json
      # Read by kickstart.json via #{ENV.X} - resolved fresh every container start,
      # so editing .env and running `docker compose up` is enough; no need to
      # regenerate kickstart.json itself for a domain/secret change to take effect.
      FUSIONAUTH_API_KEY: ${FUSIONAUTH_API_KEY}
      FUSIONAUTH_APPLICATION_ID: ${FUSIONAUTH_APPLICATION_ID}
      FUSIONAUTH_CLIENT_SECRET: ${FUSIONAUTH_CLIENT_SECRET}
      FUSIONAUTH_ADMIN_PASSWORD: ${FUSIONAUTH_ADMIN_PASSWORD}
      # Concatenation happens here (compose's ${VAR}-in-string, already proven), not
      # in the kickstart file - FusionAuth's #{ENV.X} is only confirmed to do whole-
      # value substitution, not concatenation with surrounding literal text.
      FUSIONAUTH_ISSUER: https://${FUSIONAUTH_PUBLIC_DOMAIN}
      FUSIONAUTH_REDIRECT_URL: https://${PUBLIC_DOMAIN}/api/auth/callback/fusionauth
      FUSIONAUTH_LOGOUT_URL: https://${PUBLIC_DOMAIN}
    # Also on "proxy" - end-user browsers hit FusionAuth directly for the login
    # redirect, so it needs to be externally reachable, same as seaweedfs/slackopy.
    networks:
      - default
      - proxy
    volumes:
      - fusionauth-config:/usr/local/fusionauth/config
      - ./fusionauth-kickstart.json:/usr/local/fusionauth/kickstart/kickstart.json:ro

  slackcat-slackpack:
    image: ghcr.io/mathiazom/slackpack:main
    restart: unless-stopped
    depends_on:
      slackcat-postgres:
        condition: service_healthy
    environment:
      SLACK_AUTH_TOKEN: ${SLACK_AUTH_TOKEN}
      SLACK_AUTH_COOKIE: ${SLACK_AUTH_COOKIE}
      DATABASE_CONNECTION_STRING: postgres://slackcat:${POSTGRES_PASSWORD}@slackcat-postgres:5432/slackcat
      SEAWEEDFS_MASTER_URL: http://slackcat-seaweedfs:9333

  slackcat-init-migrate:
    image: ghcr.io/mathiazom/slackpack:main
    restart: "no"
    depends_on:
      slackcat-postgres:
        condition: service_healthy
    entrypoint: ["/root/slackpack"]
    command: ["-migrate"]
    environment:
      DATABASE_CONNECTION_STRING: postgres://slackcat:${POSTGRES_PASSWORD}@slackcat-postgres:5432/slackcat

  slackcat-init-slackback-role:
    image: postgres:17-alpine
    restart: "no"
    depends_on:
      slackcat-postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    # Idempotent - safe to re-run. slackback only ever reads, so this grants SELECT
    # only, including on tables added by future migrations.
    # No PL/pgSQL DO block (dollar-quoting collides with compose's own $$-escaping)
    # and no shell variables (bare $word is interpolated by compose same as ${word})
    # - the only $ sequences below are the intentional ${POSTGRES_PASSWORD}/
    # ${SLACKBACK_DB_PASSWORD} substitutions.
    command:
      - |
        set -e
        psql "postgres://slackcat:${POSTGRES_PASSWORD}@slackcat-postgres:5432/slackcat" -c "CREATE ROLE slackback WITH LOGIN PASSWORD '${SLACKBACK_DB_PASSWORD}'" || \
          psql "postgres://slackcat:${POSTGRES_PASSWORD}@slackcat-postgres:5432/slackcat" -c "ALTER ROLE slackback WITH LOGIN PASSWORD '${SLACKBACK_DB_PASSWORD}'"
        psql "postgres://slackcat:${POSTGRES_PASSWORD}@slackcat-postgres:5432/slackcat" -c "GRANT CONNECT ON DATABASE slackcat TO slackback"
        psql "postgres://slackcat:${POSTGRES_PASSWORD}@slackcat-postgres:5432/slackcat" -c "GRANT USAGE ON SCHEMA public TO slackback"
        psql "postgres://slackcat:${POSTGRES_PASSWORD}@slackcat-postgres:5432/slackcat" -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO slackback"
        psql "postgres://slackcat:${POSTGRES_PASSWORD}@slackcat-postgres:5432/slackcat" -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO slackback"

  slackcat-slackback:
    image: ghcr.io/mathiazom/slackback:main
    restart: unless-stopped
    depends_on:
      slackcat-postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__Postgres: Host=slackcat-postgres;Port=5432;Username=slackback;Password=${SLACKBACK_DB_PASSWORD};Database=slackcat
      SeaweedFs__PublicUrl: https://${FILES_PUBLIC_DOMAIN}

  slackcat-slackopy:
    image: ghcr.io/mathiazom/slackopy:main
    restart: unless-stopped
    depends_on:
      - slackcat-slackback
      - slackcat-fusionauth
    environment:
      BACKEND_URL: http://slackcat-slackback:8080
      HOST_URL: https://${PUBLIC_DOMAIN}
      AUTH_SECRET: ${AUTH_SECRET}
      FUSIONAUTH_CLIENT_ID: ${FUSIONAUTH_APPLICATION_ID}
      FUSIONAUTH_CLIENT_SECRET: ${FUSIONAUTH_CLIENT_SECRET}
      FUSIONAUTH_URL: https://${FUSIONAUTH_PUBLIC_DOMAIN}
    # Also on "proxy" - this is the one end-user-facing entry point into the whole
    # system.
    networks:
      - default
      - proxy

volumes:
  postgres-data:
  seaweedfs-data:
  fusionauth-db-data:
  fusionauth-config:

networks:
  # Internal-only network for services that only ever talk to each other
  # (postgres, slackpack, slackback, ...) - never joined by anything outside this
  # deployment.
  default:
    name: slackcat
  # The admin's own already-existing reverse-proxy network (Nginx Proxy Manager,
  # Traefik, etc.) - this deployment joins it, matching how these proxies are
  # conventionally run: the proxy is the shared, standing infrastructure that many
  # apps attach to, not something that goes looking for each app's own network.
  proxy:
    external: true
    name: ${REVERSE_PROXY_NETWORK}
COMPOSEEOF

# Fully static template - deliberately no shell substitution here (quoted heredoc
# delimiter). Every value that varies per deployment is resolved by FusionAuth's own
# #{ENV.X} kickstart syntax from the fusionauth container's actual environment at
# container-start time, not baked in here at generation time. This means editing
# .env and running `docker compose up` is enough to pick up a changed domain/secret -
# no need to regenerate this file.
cat >"$DEPLOY_DIR/fusionauth-kickstart.json" <<'KICKSTARTEOF'
{
  "variables": {
    "apiKey": "#{ENV.FUSIONAUTH_API_KEY}",
    "applicationId": "#{ENV.FUSIONAUTH_APPLICATION_ID}",
    "clientSecret": "#{ENV.FUSIONAUTH_CLIENT_SECRET}",
    "defaultTenantId": "d7d09513-a3f5-401c-9685-34ab6c552453",
    "adminUserId": "00000000-0000-0000-0000-000000000001"
  },
  "apiKeys": [
    {
      "key": "#{apiKey}",
      "description": "Unrestricted API key"
    }
  ],
  "requests": [
    {
      "method": "PATCH",
      "url": "/api/tenant/#{defaultTenantId}",
      "body": {
        "tenant": {
          "issuer": "#{ENV.FUSIONAUTH_ISSUER}"
        }
      }
    },
    {
      "method": "POST",
      "url": "/api/application/#{applicationId}",
      "tenantId": "#{defaultTenantId}",
      "body": {
        "application": {
          "name": "slackopy",
          "oauthConfiguration": {
            "authorizedRedirectURLs": [
              "#{ENV.FUSIONAUTH_REDIRECT_URL}"
            ],
            "logoutURL": "#{ENV.FUSIONAUTH_LOGOUT_URL}",
            "clientSecret": "#{clientSecret}",
            "enabledGrants": [
              "authorization_code",
              "refresh_token"
            ],
            "generateRefreshTokens": true,
            "requireRegistration": false
          }
        }
      }
    },
    {
      "method": "POST",
      "url": "/api/user/registration/#{adminUserId}",
      "body": {
        "user": {
          "username": "admin",
          "password": "#{ENV.FUSIONAUTH_ADMIN_PASSWORD}"
        },
        "registration": {
          "applicationId": "#{FUSIONAUTH_APPLICATION_ID}",
          "roles": ["admin"]
        },
        "roles": ["admin"],
        "skipRegistrationVerification": true
      }
    }
  ]
}
KICKSTARTEOF

missing=""
for name in SLACK_AUTH_TOKEN SLACK_AUTH_COOKIE PUBLIC_DOMAIN FUSIONAUTH_PUBLIC_DOMAIN FILES_PUBLIC_DOMAIN REVERSE_PROXY_NETWORK; do
	eval "value=\${$name:-}"
	if [ -z "$value" ]; then
		missing="$missing $name"
	fi
done

cat <<SUMMARYEOF

Generated in $DEPLOY_DIR:
  - .env                     (secrets generated/prompted for)
  - docker-compose.yml       (whole system - no reverse proxy bundled; see below)
  - fusionauth-kickstart.json
SUMMARYEOF

if [ -n "$missing" ]; then
	cat <<SUMMARYEOF

Still need to be filled in by hand in $ENV_FILE before starting (no attached
terminal to prompt for them just now, or they were skipped):
 $missing
SUMMARYEOF
else
	echo
	echo "Everything required is filled in - ready to run 'docker compose up -d' in $DEPLOY_DIR."
fi

cat <<SUMMARYEOF

FusionAuth admin login (once running, at https://$FUSIONAUTH_PUBLIC_DOMAIN/admin):
  username: admin
  password: $FUSIONAUTH_ADMIN_PASSWORD
This password is also saved in $ENV_FILE as FUSIONAUTH_ADMIN_PASSWORD - kickstart only
runs once against a fresh FusionAuth instance, so changing it there later has no
effect; change it from the admin console instead.
SUMMARYEOF

cat <<SUMMARYEOF

No host ports are published. This deployment joins REVERSE_PROXY_NETWORK (your
existing Nginx Proxy Manager/Traefik network) - in your proxy, point each domain at
the corresponding container name + internal port:
  PUBLIC_DOMAIN            -> slackcat-slackopy:4321
  FUSIONAUTH_PUBLIC_DOMAIN -> slackcat-fusionauth:9011
  FILES_PUBLIC_DOMAIN      -> slackcat-seaweedfs:8080
(if your reverse proxy isn't itself running in Docker, add "ports:" mappings back
to the relevant services in docker-compose.yml instead, and drop the "proxy" network
entries)

Re-running this script later preserves the secrets already generated and only
rewrites docker-compose.yml/fusionauth-kickstart.json from the current templates.
SUMMARYEOF
